### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by siready** [NLog/NLog.DiagnosticSource#1]
@snakefoot thank you for your work! I'm wondering if this package is not ready to be used in production as it's currently not published on NuGet.

**Comment by snakefoot** [comment]
I think it is production ready. It is just pure laziness that keeps it from becoming a nuget-package.

But I'm considering to rename the repository (and nuget package) to `NLog.Extensions.DiagnosticSource`.

**Comment by 304NotModified** [comment]
> But I'm considering to rename the repository (and nuget package) to `NLog.Extensions.DiagnosticSource`.

I would choose for NLog.DiagnosticSource as all the NLog.Extension packages has a dependency on Microsoft.Extensions

**Comment by snakefoot** [comment]
I was just thinking that we have `NLog.Layouts` and `NLog.Targerts` and if contains both then it is "NLog.Extensions" to match assembly-extension-loading. 

But NLog.DiagnosticSource also works

**Comment by siready** [comment]
Hey, is there a plan for the release? If I understand it correctly, it would make it the easiest way to enable correlated distributed logs via NLog, or should that be solved in some other way with NLog?

**Comment by 304NotModified** [comment]
Will try to do this, this weekend

**Comment by 304NotModified** [comment]
I had no time to double check the package in debt, so I made a 1.0.0-rc.1 version. (all done on mobile!)

**Comment by 304NotModified** [comment]
https://www.nuget.org/packages/NLog.DiagnosticSource

Please let me know if it all works well, then I could change it to a rtm version (after double check also from our side)

**Comment by snakefoot** [comment]
@304NotModified  Wow. That was fast. Thank you so much.

@siready Care to try it out?

**Comment by 304NotModified** [comment]
@snakefoot thanks for the initial appveyor config. Saved a lot :)

**Comment by siready** [comment]
Thanks, will check over the weekend :)

**Comment by snakefoot** [comment]
@siready Had any success with the pre-release ? or feedback on how hard/easy it is to use?

**Comment by snakefoot** [comment]
@siready How is the testing going?

**Comment by 304NotModified** [comment]
@siready  any news? Happy with the package?

**Comment by snakefoot** [comment]
@siready NLog.DiagnosticSource ver. 1.0.0-rc.2 is now available on nuget: https://www.nuget.org/packages/NLog.DiagnosticSource

It changes `SpanId` (Merges SpanId with Id), ParentId (Merged with ParentSpanId) and TraceId (Merges with RootSpanId) so output matches the values from AspNetCore3 (and later).

**Comment by snakefoot** [comment]
Ver. 1.0.0 has now been released:

https://www.nuget.org/packages/NLog.DiagnosticSource
