### ISSUE TITLE
Nuget push failed (403)

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.DiagnosticSource#23]
[Log](https://ci.appveyor.com/project/nlog/nlog-diagnosticsource/builds/36457947):
> `Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.`

_Originally posted by @snakefoot in https://github.com/NLog/NLog.DiagnosticSource/issues/22#issuecomment-731993313_

**Comment by 304NotModified** [comment]
Stupid autocorrect ':)

**Comment by 304NotModified** [comment]
@snakefoot I will try to find the issue, but I checked all steps and don't get it. 

Will do a double check.

**Comment by 304NotModified** [comment]
> Deploying using NuGet provider
Publishing NLog.DiagnosticSource.1.0.0-rc.2.nupkg to https://www.nuget.org/api/v2/package...OK
Publishing NLog.DiagnosticSource.1.0.0-rc.2.snupkg to https://www.nuget.org/api/v2/symbolpackage...OK
Total packages published: 2
Build success

Fixed :)

**Comment by snakefoot** [comment]
Yes it looks great. First package with Net5.0-support
